# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_auto_20151215_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, b'bad'), (2, b'poor'), (3, b'regular'), (4, b'good'), (5, b'gorgeus')], default=1)),
                ('date_rated', models.DateTimeField(editable=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_movie', to='booking.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
