# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='show',
            new_name='movie',
        ),
    ]
