# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20151215_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_rated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
