# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20151215_2248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('movie', 'user')]),
        ),
    ]
