# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20151212_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='image_thumbnail',
            new_name='image',
        ),
    ]
