# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, upload_to=b'movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='screening_end',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
