# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 14:23
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20151211_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.get_image_path),
        ),
    ]
