# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review_grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
