# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='city',
            field=models.CharField(default='Zagreb', max_length=255),
            preserve_default=False,
        ),
    ]
