# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_movie_age_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
