# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20151215_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_grade',
        ),
    ]
