# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_movie_review_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('sorted', django.db.models.manager.Manager()),
            ],
        ),
    ]
