# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20151215_2322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
    ]
