# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20151216_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='seat',
            name='rowNumber',
            field=models.CharField(default='a11', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
