# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20160121_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('rowNumber', 'screenings')]),
        ),
    ]
